### ISSUE TITLE
[Bug] [Self-Hosted] appflowy_cloud issues when minio url has an underscore

### ISSUE THREAD

**Issue by Diamon0** [AppFlowy-IO/AppFlowy-Cloud#1177]
**Describe the bug**
After upgrading from an older version to a newer version of the appflowy image, including updating the docker-compose.yml, .env, and nginx/nginx.conf files, appflowy_cloud has issues with the "Unhandle s3 service error", invalid request and invalid hostname.

**To Reproduce**
1. Set up self-hosted with an older version of the minio bucket

**Expected behavior**
No errors when appflowy_cloud tries to work with minio.

**Screenshots (sort of)**
Here is a log of the error code

```
appflowy_cloud  | AppFlowy Cloud with RUST_LOG=info
appflowy_cloud  | {"timestamp":"2025-01-19T01:25:02.891325Z","level":"INFO","fields":{"message":"Preparing to run database migrations..."},"target":"appflowy_cloud::application","filename":"src/application.rs","line_number":209}
appflowy_cloud  | {"timestamp":"2025-01-19T01:25:02.891361Z","level":"INFO","fields":{"message":"Connecting to postgres database with setting: DatabaseSetting { pg_conn_opts: PgConnectOptions { host: \"appflowy_postgres\", port: 5432, socket: None, username: \"postgres\", password: Some(\"********\"), database: Some(\"postgres\"), ssl_mode: Prefer, ssl_root_cert: None, ssl_client_cert: None, ssl_client_key: None, statement_cache_capacity: 100, application_name: None, log_settings: LogSettings { statements_level: Debug, slow_statements_level: Warn, slow_statements_duration: 1s }, extra_float_digits: Some(\"2\"), options: None }, require_ssl: false, max_connections: 40 }"},"target":"appflowy_cloud::application","filename":"src/application.rs","line_number":513}
appflowy_cloud  | {"timestamp":"2025-01-19T01:25:02.898348Z","level":"INFO","fields":{"message":"Setting up S3 bucket..."},"target":"appflowy_cloud::application","filename":"src/application.rs","line_number":214}
appflowy_cloud  | {"timestamp":"2025-01-19T01:25:02.909857Z","level":"ERROR","fields":{"message":"Unhandle s3 service error: ServiceError(ServiceError { source: Unhandled(Unhandled { source: ErrorMetadata { code: Some(\"InvalidRequest\"), message: Some(\"Invalid Request (invalid hostname)\"), extras: Some({\"s3_extended_request_id\": \"dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8\", \"aws_request_id\": \"181BF3951479B55A\"}) }, meta: ErrorMetadata { code: Some(\"InvalidRequest\"), message: Some(\"Invalid Request (invalid hostname)\"), extras: Some({\"s3_extended_request_id\": \"dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8\", \"aws_request_id\": \"181BF3951479B55A\"}) } }), raw: Response { status: StatusCode(400), headers: Headers { headers: {\"accept-ranges\": HeaderValue { _private: H0(\"bytes\") }, \"content-length\": HeaderValue { _private: H0(\"285\") }, \"content-type\": HeaderValue { _private: H0(\"application/xml\") }, \"server\": HeaderValue { _private: H0(\"MinIO\") }, \"strict-transport-security\": HeaderValue { _private: H0(\"max-age=31536000; includeSubDomains\") }, \"vary\": HeaderValue { _private: H0(\"Origin\") }, \"x-amz-id-2\": HeaderValue { _private: H0(\"dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8\") }, \"x-amz-request-id\": HeaderValue { _private: H0(\"181BF3951479B55A\") }, \"x-content-type-options\": HeaderValue { _private: H0(\"nosniff\") }, \"x-xss-protection\": HeaderValue { _private: H0(\"1; mode=block\") }, \"date\": HeaderValue { _private: H0(\"Sun, 19 Jan 2025 01:25:02 GMT\") }} }, body: SdkBody { inner: Once(Some(b\"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<Error><Code>InvalidRequest</Code><Message>Invalid Request (invalid hostname)</Message><Resource>/appflowy/</Resource><RequestId>181BF3951479B55A</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>\")), retryable: true }, extensions: Extensions { extensions_02x: Extensions, extensions_1x: Extensions } } })"},"target":"appflowy_cloud::application","filename":"src/application.rs","line_number":485}
appflowy_cloud  | Error: Failed to initialize application state: service error
appflowy_cloud  | 
appflowy_cloud  | Stack backtrace:
appflowy_cloud  |    0: anyhow::kind::Adhoc::new
appflowy_cloud  |    1: tokio::task::local::LocalSet::run_until::{{closure}}
appflowy_cloud  |    2: appflowy_cloud::main
appflowy_cloud  |    3: std::sys::backtrace::__rust_begin_short_backtrace
appflowy_cloud  |    4: main
appflowy_cloud  |    5: <unknown>
appflowy_cloud  |    6: __libc_start_main
appflowy_cloud  |    7: _start

```

**Desktop (please complete the following information):**
 - Official Docker Image

**Additional context**
I am using everything inside a network called "proxiable", and added a container_name to every container with the naming schema "appflowy_x", not adding another "appflowy_" if they already have it

Here is the appflowy_cloud section of the docker-compose.yml file
```
appflowy_cloud:
    container_name: appflowy_cloud
    restart: on-failure
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - APPFLOWY_ENVIRONMENT=production
      - APPFLOWY_DATABASE_URL=${APPFLOWY_DATABASE_URL}
      - APPFLOWY_REDIS_URI=${APPFLOWY_REDIS_URI}
      - APPFLOWY_GOTRUE_JWT_SECRET=${GOTRUE_JWT_SECRET}
      - APPFLOWY_GOTRUE_JWT_EXP=${GOTRUE_JWT_EXP}
      - APPFLOWY_GOTRUE_BASE_URL=${APPFLOWY_GOTRUE_BASE_URL}
      - APPFLOWY_GOTRUE_EXT_URL=${API_EXTERNAL_URL}
      - APPFLOWY_GOTRUE_ADMIN_EMAIL=${GOTRUE_ADMIN_EMAIL}
      - APPFLOWY_GOTRUE_ADMIN_PASSWORD=${GOTRUE_ADMIN_PASSWORD}
      - APPFLOWY_S3_CREATE_BUCKET=${APPFLOWY_S3_CREATE_BUCKET}
      - APPFLOWY_S3_USE_MINIO=${APPFLOWY_S3_USE_MINIO}
      - APPFLOWY_S3_MINIO_URL=${APPFLOWY_S3_MINIO_URL}
      - APPFLOWY_S3_ACCESS_KEY=${APPFLOWY_S3_ACCESS_KEY}
      - APPFLOWY_S3_SECRET_KEY=${APPFLOWY_S3_SECRET_KEY}
      - APPFLOWY_S3_BUCKET=${APPFLOWY_S3_BUCKET}
      - APPFLOWY_S3_REGION=${APPFLOWY_S3_REGION}
      - APPFLOWY_MAILER_SMTP_HOST=${APPFLOWY_MAILER_SMTP_HOST}
      - APPFLOWY_MAILER_SMTP_PORT=${APPFLOWY_MAILER_SMTP_PORT}
      - APPFLOWY_MAILER_SMTP_USERNAME=${APPFLOWY_MAILER_SMTP_USERNAME}
      - APPFLOWY_MAILER_SMTP_EMAIL=${APPFLOWY_MAILER_SMTP_EMAIL}
      - APPFLOWY_MAILER_SMTP_PASSWORD=${APPFLOWY_MAILER_SMTP_PASSWORD}
      - APPFLOWY_MAILER_SMTP_TLS_KIND=${APPFLOWY_MAILER_SMTP_TLS_KIND}
      - APPFLOWY_ACCESS_CONTROL=${APPFLOWY_ACCESS_CONTROL}
      - APPFLOWY_DATABASE_MAX_CONNECTIONS=${APPFLOWY_DATABASE_MAX_CONNECTIONS}
      - AI_SERVER_HOST=${AI_SERVER_HOST}
      - AI_SERVER_PORT=${AI_SERVER_PORT}
      - AI_OPENAI_API_KEY=${AI_OPENAI_API_KEY}
      # Uncomment this line if AppFlowy Web has been deployed
      # - APPFLOWY_WEB_URL=${APPFLOWY_WEB_URL}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FEATURES: ""
    image: appflowyinc/appflowy_cloud:${APPFLOWY_CLOUD_VERSION:-latest}
    networks:
      - proxiable
```

The minio section:
```
minio:
    container_name: appflowy_minio
    restart: on-failure
    image: minio/minio
    environment:
      - MINIO_BROWSER_REDIRECT_URL=${FQDN?:err}/minio
      - MINIO_ROOT_USER=${APPFLOWY_S3_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${APPFLOWY_S3_SECRET_KEY:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - proxiable
```

For the .env file, here is the relevant data:
```
# Minio Host
MINIO_HOST=appflowy_minio
MINIO_PORT=9000

# File Storage
# Create the bucket if not exists on AppFlowy Cloud start up.
# Set this to false if the bucket has been created externally.
APPFLOWY_S3_CREATE_BUCKET=true
# This is where storage like images, files, etc. will be stored.
# By default, Minio is used as the default file storage which uses host's file system.
# Keep this as true if you are using other S3 compatible storage provider other than AWS.
APPFLOWY_S3_USE_MINIO=true
APPFLOWY_S3_MINIO_URL=http://${MINIO_HOST}:${MINIO_PORT}
APPFLOWY_S3_ACCESS_KEY=${AWS_ACCESS_KEY}
APPFLOWY_S3_SECRET_KEY=${AWS_SECRET}
APPFLOWY_S3_BUCKET=appflowy
#APPFLOWY_S3_REGION=us-east-1
```

And inside the nginx/nginx.conf file:
```
set $minio_backend "http://appflowy_minio:9001";
location /minio/ {
            proxy_pass $minio_backend; 

            rewrite ^/minio/(.*) /$1 break; 
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-NginX-Proxy true;
         
            ## This is necessary to pass the correct IP to be hashed
            real_ip_header X-Real-IP;
        
            proxy_connect_timeout 300;

            ## To support websockets in MinIO versions released after January 2023
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            # Some environments may encounter CORS errors (Kubernetes + Nginx Ingress)
            # Uncomment the following line to set the Origin request to an empty string
            # proxy_set_header Origin '';

            chunked_transfer_encoding off;
        }
```
