### ISSUE TITLE
[Bug] Self Hosted Postgres and Minio docker not starting (Proxmox LXC SMB share)

### ISSUE THREAD

**Issue by sarulnat** [AppFlowy-IO/AppFlowy-Cloud#1198]
**Describe the bug**
Initial docker setup keeps failing for Postgres and Minio containers. I am running the docker containers inside a proxmox unprivileged LXC. I wanted to add external storage volumes to store data and files. There is a SMB share being mounted in the proxmox host and then passed into the LXC with the right user mappings (to deal with lxc unprivileged 100000 user ids). Read write access to the SMB share from inside the LXC container has been confirmed.

i'm not sure if it's because of my smb and lxc setup, but postgres and minio would not launch as containers (unhealthy) after I passed the volumes like this in docker-compose.yml.
```
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /local/path/to/postgres_data
      o: bind
  minio_data:
    driver: local
    driver_opts:
      type: none
      device: /local/path/to/minio_data
      o: bind
```

**To Reproduce**
1. Setup docker environment as Proxmox unprivileged LXC, connect SMB shares and passthrough to LXC.
2. Followed self-host deployment instructions https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/doc/DEPLOYMENT.md
3. docker compose up -d
4. minio and postgres containers fail to startup.

**Expected behavior**
Minio and postgres launch in healthy state.

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 12 (bookworm)
 - LXC unprivileged container inside Proxmox

**Fix**
Seems to be fixed when i change the volumes section in the postgres docker-compose
from postgres_data:/var/lib/postgresql/data
to postgres_data:/var/lib/postgresql
