### ISSUE TITLE
FQDN is a URL and not a fully-qualified domain name

### ISSUE THREAD

**Issue by almereyda** [AppFlowy-IO/AppFlowy-Cloud#1248]
Because I had previously introduced an `FQDN` variable for configuring a Traefik router, this broke after the recent introduction of this variable here in my upstream.

The variable is actually a full URL that also includes the scheme, why parsing the string as an FQDN fails. This semantic ambiguity can be resolved with introducing another variable `APPFLOWY_PUBLIC_URL` or similar.

```diff
< FQDN=http://localhost
---
> FQDN=appflowy.example.org
> APPFLOWY_PUBLIC_URL=https://${FQDN}
```

```diff
< API_EXTERNAL_URL=${FQDN}/gotrue
---
> API_EXTERNAL_URL=${APPFLOWY_PUBLIC_URL}/gotrue
```

```diff
< # APPFLOWY_S3_PRESIGNED_URL_ENDPOINT=${FQDN}/minio-api
---
> # APPFLOWY_S3_PRESIGNED_URL_ENDPOINT=${APPFLOWY_S3_MINIO_URL}
```

```diff
< APPFLOWY_WEB_URL=${FQDN}
---
> APPFLOWY_WEB_URL=${APPFLOWY_PUBLIC_URL}
```

This setup is very specific to not running with Minio #1247 and trimming down nginx.conf #1246

These adaptations allow to run the nginx container with an FQDN as Traefik host rule:

```yaml
    labels:
      traefik.enable: true
      traefik.http.routers.org-example-appflowy-web.entrypoints: web
      traefik.http.routers.org-example-appflowy-web.rule: Host(`${FQDN}`)
      traefik.http.routers.org-example-appflowy-web.middlewares: http-to-https
      traefik.http.middlewares.http-to-https.redirectscheme.scheme: https
      traefik.http.middlewares.http-to-https.redirectscheme.permanent: true
      traefik.http.routers.org-example-appflowy-webs.entrypoints: webs
      traefik.http.routers.org-example-appflowy-webs.rule: Host(`${FQDN}`)
      traefik.http.routers.org-example-appflowy-webs.tls: true
      traefik.http.routers.org-example-appflowy-webs.tls.certresolver: le
```
