### ISSUE TITLE
Request failed with status code 405

### ISSUE THREAD

**Issue by tradethongminh** [AppFlowy-IO/AppFlowy-Cloud#1385]
I have deployed AppFlowy using Docker and configured the .env file with the following values:

```
GOTRUE_SMTP_HOST=smtp.gmail.com
GOTRUE_SMTP_PORT=465
GOTRUE_MAILER_SMTP_TLS_KIND=wrapper
GOTRUE_SMTP_USER=mailxxx@gmail.com
GOTRUE_SMTP_PASS=<app_password_16words>
GOTRUE_SMTP_ADMIN_EMAIL=mailxxx@gmail.com
GOTRUE_MAILER_AUTOCONFIRM=true
GOTRUE_ADMIN_EMAIL=mailxxx@gmail.com
GOTRUE_ADMIN_PASSWORD=xxxx#yyyyy

```
In my docker-compose.yml, I added the following service:
```
  appflowy_web:
    image: appflowyinc/appflowy_web:${APPFLOWY_WEB_VERSION:-latest}
    restart: on-failure
    environment:
      - APPFLOWY_GOTRUE_BASE_URL=http://gotrue:9999
    depends_on:
      - appflowy_cloud
    ports:
      - "3000:80"
```
When I access http://192.168.1.66:3000/ and enter an email address, then click login, I receive the error:

> Request failed with status code 405

Also, the admin interface at http://192.168.1.66:3000/console does not provide any option to log in using email and password.

![Image](https://github.com/user-attachments/assets/55d3dd2b-a168-4fad-b197-8ac14a6d0e32)
![Image](https://github.com/user-attachments/assets/4fdffa61-174a-482a-af07-54b38ba7e78c)

I did not configure Nginx because I only intend to access AppFlowy within the local network.

Please help me understand what might be misconfigured or missing in order to successfully complete the login flow.

Let me know if you’d like to include screenshots or logs along with this.
