### ISSUE TITLE
[FR] Docker healthchecks for all containers

### ISSUE THREAD

**Issue by alx-xlx** [AppFlowy-IO/AppFlowy-Cloud#1398]
Please add support for healthchecks for all containers

Only `appflowy-gotrue` and `appflowy-db` have healthchecks support as of now

```
appflowy-web - Up 11 minutes
appflowy-admin - Up 11 minutes
appflowy-cloud - Up 11 minutes
appflowy-gotrue - Up 11 minutes (healthy)
appflowy-ai - Up 11 minutes
appflowy-worker - Up 11 minutes
appflowy-minio - Up 11 minutes
appflowy-redis - Up 11 minutes
appflowy-db - Up 11 minutes (healthy)
appflowy-nginx - Up 11 minutes
```

**Comment by r4nchy** [comment]
here is what I was able to add and it worked for some but not for others

```yaml
services:
  nginx:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  minio:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s

  postgres:
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 12

  redis:
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s

  gotrue:
    healthcheck:
      test: "curl --fail http://127.0.0.1:9999/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 12

```
