### ISSUE TITLE
[Bug] GoTrue Server Healthcheck Fails on Startup

### ISSUE THREAD

**Issue by AMDphreak** [AppFlowy-IO/AppFlowy-Cloud#1498]
Likely cause: GoTrue docker wait timer is too short

Bug Report: GoTrue Server Healthcheck Fails on Startup
Title: GoTrue Server Healthcheck Fails Due to Extended Startup Time, Disrupting Dependent Services

**Problem Description:**

The GoTrue authentication server in AppFlowy's Docker Compose deployment frequently reports as `unhealthy` prematurely during its initial startup phase. This occurs because its full initialization time exceeds current healthcheck parameters, preventing dependent services (e.g., `appflowy-cloud`) from connecting. This often necessitates manual intervention (`docker compose up --force-recreate` or repeated use of `docker compose up -d`) for the stack to become fully operational.

**Steps to Reproduce:**

1. Use `docker-compose.yml` with GoTrue and dependent services.
2. Run `docker compose down --volumes`.
3. Execute `docker compose up -d`.
4. Observe `docker compose ps` and `docker compose logs` for GoTrue's `unhealthy` status and dependent service connection failures.
5. Note that the stack may not self-recover.

**Expected Behavior:**

GoTrue should be given adequate time to initialize, and dependent services should wait for GoTrue to report `healthy` for seamless stack startup.

**Actual Behavior:**

GoTrue is marked `unhealthy` too quickly, causing dependent service failures and requiring manual restarts.

**Proposed Solution:**

Adjust GoTrue's `healthcheck` parameters in `docker-compose.yml`, specifically increasing `start_period` to accommodate its longer initialization time.

Example `healthcheck` adjustments for `gotrue` service:

```yml
services:
  gotrue:
    # ... other GoTrue configurations
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health"] # Verify port and endpoint
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s  # Allow 2 minutes for initial startup
    # ...
```

**Environment:**

- **Application**: AppFlowy (latest stable)
- **Deployment**: Docker Compose
- **Operating System**: [User's OS, e.g., Ubuntu 22.04, macOS, Windows with WSL2]
- **Docker Version**: [e.g., Docker Engine 24.0.5, Docker Compose v2.20.2]

**Screenshots**

![Image](https://github.com/user-attachments/assets/363cff97-e543-4a05-a537-28a9239e2d1b)

**Desktop (please complete the following information):**
 - OS: AlmaLinux 9
 - Version: latest
