### ISSUE TITLE
How do you use a postgres database with the cloud image?

### ISSUE THREAD

**Issue by jessebot** [AppFlowy-IO/AppFlowy-Cloud#198]
# Preamble

First of all, this isn't a bug, more of a series of questions. Second of all, thanks for working on appflowy! It seems really nice :) Third of all, sorry for all the text, there's just a lot of context necessary to communicate what's going on and why.

According to the docs, only docker-compose is supported right now, which is fine, however my project does everything on kubernetes, so I've been working on both [gotrue](https://github.com/jessebot/gotrue-helm/) and [appflowy-cloud](https://github.com/jessebot/appflowy-helm/tree/adding-initial-commit-of-helm-chart) helm charts, in order to test both at the same time. gotrue is about where it needs to be, but appflowy is still throwing a few errors, however, they seem pretty reasonable and easy to move past. So, just have a few questions.

### Context and Errors

My appflowy-cloud container in my k8s deployment's pod keeps throwing these errors:

<details>
<summary>Click me for logs showing postgres connection error</summary>

```logtalk
AppFlowy Cloud with RUST_LOG=info

{"timestamp":"2023-12-06T15:52:52.168734Z","level":"INFO","fields":{"message":"Connecting to postgres database with setting: DatabaseSetting { username: \"postgres\", password: \"password\", port: 5432, host: \"postgres\", database_name: \"postgres\", require_ssl: false, max_connections: 20 }"},"target":"appflowy_cloud::application"}

{"v":0,"name":"appflowy_cloud","msg":"Connecting to postgres database with setting: DatabaseSetting { username: \"postgres\", password: \"password\", port: 5432, host: \"postgres\", database_name: \"postgres\", require_ssl: false, max_connections: 20 }","level":30,"hostname":"appflowy-web-app-cloud-c996cbc6f-gf4h4","pid":1,"time":"2023-12-06T15:52:52.168771033Z","target":"appflowy_cloud::application","line":316,"file":"src/application.rs"}

thread 'main' panicked at 'The AppState should be initialized: failed to connect to postgres database

Caused by:

    0: error communicating with database: failed to lookup address information: Name or service not known

    1: failed to lookup address information: Name or service not known', src/main.rs:29:6

stack backtrace:

   0: rust_begin_unwind

             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5

   1: core::panicking::panic_fmt

             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14

   2: core::result::unwrap_failed

             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5

   3: tokio::task::local::LocalSet::run_until::{{closure}}

   4: appflowy_cloud::main

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>
 
 I know k8s isn't supported yet, but here's my deployment file if you'd like:
 
 <details>
  <summary>click me for the full k8s deployment</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appflowy-web-app-cloud
  namespace: appflowy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - env:
        - name: APP_ENVIRONMENT
          value: production
        - name: RUST_LOG
          value: info
        - name: APP__GOTRUE__ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              key: adminEmail
              name: appflowy-gotrue-credentials
        - name: APP__GOTRUE__ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: adminPassword
              name: appflowy-gotrue-credentials
        - name: APP__GOTRUE__JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: jwtSecret
              name: appflowy-gotrue-credentials
        - name: APP__GOTRUE__EXT_URL
          valueFrom:
            secretKeyRef:
              key: externalUrl
              name: appflowy-gotrue-credentials
        - name: APP__S3__USE_MINIO
          value: "true"
        - name: APP__S3__AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: accessKeyId
              name: appflowy-s3-credentials
        - name: APP__S3__AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: secretAccessKey
              name: appflowy-s3-credentials
        - name: APP__S3__AWS_REGION
          valueFrom:
            secretKeyRef:
              key: region
              name: appflowy-s3-credentials
        - name: APP__S3__AWS_BUCKET
          valueFrom:
            secretKeyRef:
              key: bucket
              name: appflowy-s3-credentials
        - name: APP__S3__MINIO_URL
          valueFrom:
            secretKeyRef:
              key: endpoint
              name: appflowy-s3-credentials
        image: appflowyinc/appflowy_cloud:0.0.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: appflowy
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: appflowy-web-app
      serviceAccountName: appflowy-web-app
      terminationGracePeriodSeconds: 30
```
</details>

**Desktop (please complete the following information):**
 - OS: debian running k3s which is running a deployment which is running the appflowy-cloud container in a pod
 - Version: `appflowyinc/appflowy_cloud:0.0.2`

# Actual Questions

I assume this is because it needs a database, however, how do I pass in those credentials to appflowy container?

1. Should I just use [postgres env vars](https://www.postgresql.org/docs/current/libpq-envars.html)?

2. What needs to be done to setup the database? In the docs it shows running `sqlx migrate run`
and `cargo sqlx prepare --workspace`. What is that doing? Is it just running all the sql scripts [here](https://github.com/AppFlowy-IO/AppFlowy-Cloud/tree/main/migrations)?
  
3. How would you recommend doing this decoratively? Should I use a rust container to install `sqlx-cli`, have the scripts mounted as volumes, and then run `sqlx migrate run` and `cargo sqlx prepare --workspace`? Do those commands need admin access to the postgres server? Do I need to include any other files to do this?

4. can these db migration scripts be something that the container does by default one day? That would save needing to maintain an image just for this. I could also be happy to help with this, but I am pretty new to rust, so I would have more follow up questions 🙏 

# Parting Thoughts
1. Extremely minor: Could you also please enable Discussions on this repo so that we can chat without needing to create a bug report? I just don't want to scare any of the maintainers for a question, but I think keeping it on GitHub is really good for others searching for help near the source.

2. After I'm done working on the helm chart, would you be interested in me donating it to this project? If not, would you like help working on a helm chart for this? It would increase adoption and I'd love to help you out if you'd like (I'm a devops engineer by trade) 🙏
