### ISSUE TITLE
[Bug] minio with TLS usage results in: `error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed`

### ISSUE THREAD

**Issue by jessebot** [AppFlowy-IO/AppFlowy-Cloud#204]
# Description
When using minio with TLS with the appflowy-cloud image, I always seem to get:

> error sending request for url (https://s3-appflowy.buildstars.online/appflowy): error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: (unable to get local issuer certificate)

I don't know if it's related this issue, https://github.com/durch/rust-s3/issues/291, but I guessed based on https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/9589054f3874c60063878f084af01905b182d537/Cargo.toml#L56

I don't think I know enough rust yet to dig too deep into this one, but I assume the issue happens somewhere in here:
https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/src/application.rs

## To Reproduce

1. create a postgres cluster for gotrue and appflowy to use (I'm using a [postgresql cluster Argo CD ApplicationSet](https://github.com/small-hack/argocd-apps/blob/main/demo/appflowy/app_of_apps/postgres_argocd_appset.yaml))

2. spinup gotrue (I'm doing this via a [gotrue Argo CD ApplicationSet](https://github.com/small-hack/argocd-apps/blob/main/demo/appflowy/app_of_apps/gotrue_argocd_appset.yaml) using the helm chart I wrote)

3. spin up minio using the [community helm chart](https://github.com/minio/minio/tree/master/helm/minio) (in my case, I'm doing this via a [minio Argo CD ApplicationSet](https://github.com/small-hack/argocd-apps/blob/main/demo/appflowy/storage/minio/minio_argocd_appset.yaml)). I'm using it to create:

- appflowy bucket
- appflowy read and write policy for the appflowy bucket

<details>
  <summary>write appflowy policy for reference</summary>
  
```yaml
# this is in yaml because it's applied via the helm chart
- name: writeappflowypolicy
  statements:
    - effect: Allow  # this is the default
      resources:
        - 'arn:aws:s3:::appflowy*/*'
      actions:
        - "s3:AbortMultipartUpload"
        - "s3:GetObject"
        - "s3:DeleteObject"
        - "s3:PutObject"
        - "s3:ListMultipartUploadParts"
    - resources:
        - 'arn:aws:s3:::appflowy*'
      actions:
        - "s3:CreateBucket"
        - "s3:DeleteBucket"
        - "s3:GetBucketLocation"
        - "s3:ListBucket"
        - "s3:ListBucketMultipartUploads"
```

</details>

- appflowy user with access key and secret key and assigned appflowy policy

4. spin up appflowy, which I'm also doing via an [Appflowy Argo CD ApplicationSet](https://github.com/small-hack/argocd-apps/blob/main/demo/appflowy/app_of_apps/appflowy_argocd_appset.yaml) which uses the [helm chart](https://github.com/jessebot/appflowy-helm/tree/adding-initial-commit-of-helm-chart/charts/appflowy) I'm still working on.

<details>
  <summary>full rendered appflowy-cloud deployment.yaml</summary>

```yaml
# I've stripped out empty or cluster specific values below
# this is also before trying to mount the minio certs to /usr/local/ssl/certs
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appflowy-web-app-cloud
  namespace: appflowy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: appflowy-web-app
      app.kubernetes.io/name: appflowy
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: appflowy-web-app
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: appflowy
        app.kubernetes.io/version: 0.0.2
        helm.sh/chart: appflowy-0.1.0
    spec:
      containers:
      - env:
        - name: APP_ENVIRONMENT
          value: production
        - name: RUST_LOG
          value: debug
        - name: APP__GOTRUE__ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              key: adminEmail
              name: appflowy-gotrue-credentials
        - name: APP__GOTRUE__ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: adminPassword
              name: appflowy-gotrue-credentials
        - name: APP__GOTRUE__JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: jwtSecret
              name: appflowy-gotrue-credentials
        - name: APP__GOTRUE__EXT_URL
          value: http://0.0.0.0:9999
        - name: APP__S3__USE_MINIO
          value: "true"
        - name: APP__S3__AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: accessKeyId
              name: appflowy-s3-credentials
        - name: APP__S3__AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: secretAccessKey
              name: appflowy-s3-credentials
        - name: APP__S3__AWS_REGION
          valueFrom:
            secretKeyRef:
              key: region
              name: appflowy-s3-credentials
        - name: APP__S3__AWS_BUCKET
          valueFrom:
            secretKeyRef:
              key: bucket
              name: appflowy-s3-credentials
        - name: APP__S3__MINIO_URL
          valueFrom:
            secretKeyRef:
              key: endpoint
              name: appflowy-s3-credentials
        - name: PGSSLMODE
          value: verify-full
        - name: PGSSLCERT
          value: /etc/secrets/postgres/tls.crt
        - name: PGSSLKEY
          value: /etc/secrets/postgres/tls.key
        - name: PGSSLROOTCERT
          value: /etc/secrets/ca/ca.crt
        - name: APP__DATABASE__REQUIRE_SSL
          value: "true"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: appflowy-db-secret
        - name: APP__DATABASE__HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: appflowy-db-secret
        - name: APP__DATABASE__PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: appflowy-db-secret
        - name: APP__DATABASE__USERNAME
          valueFrom:
            secretKeyRef:
              key: user
              name: appflowy-db-secret
        - name: APP__DATABASE__DATABASE_NAME
          valueFrom:
            secretKeyRef:
              key: database
              name: appflowy-db-secret
        image: appflowyinc/appflowy_cloud:0.0.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 15
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: appflowy
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 15
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /etc/secrets/ca
          name: postgres-ca
        - mountPath: /etc/secrets/postgres
          name: postgres-client-certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: appflowy-web-app
      serviceAccountName: appflowy-web-app
      terminationGracePeriodSeconds: 30
      volumes:
      - name: postgres-ca
        secret:
          defaultMode: 416
          secretName: appflowy-postgres-server-ca-key-pair
      - name: postgres-client-certs
        secret:
          defaultMode: 416
          secretName: appflowy-postgres-postgres-cert
```

</details>

Full logs from the appflowy-cloud container (postgres is finally working though! 🎉 ):
```logtalk
AppFlowy Cloud with RUST_LOG=debug

{"timestamp":"2023-12-11T09:17:45.866001Z","level":"INFO","fields":{"message":"Connecting to postgres database with setting: DatabaseSetting { username: \"postgres\", password: \"password\", port: 5432, host: \"appflowy-postgres-rw.appflowy.svc\", database_name: \"appflowy\", require_ssl: true, max_connections: 20 }"},"target":"appflowy_cloud::application"}

{"v":0,"name":"appflowy_cloud","msg":"Connecting to postgres database with setting: DatabaseSetting { username: \"postgres\", password: \"password\", port: 5432, host: \"appflowy-postgres-rw.appflowy.svc\", database_name: \"appflowy\", require_ssl: true, max_connections: 20 }","level":30,"hostname":"appflowy-web-app-cloud-7bc64fbc88-n4jlh","pid":1,"time":"2023-12-11T09:17:45.866036178Z","target":"appflowy_cloud::application","line":316,"file":"src/application.rs"}

thread 'main' panicked at 'The AppState should be initialized: reqwest: error sending request for url (https://s3-appflowy.buildstars.online/appflowy): error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: (unable to get local issuer certificate)

Caused by:

    0: error sending request for url (https://s3-appflowy.buildstars.online/appflowy): error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: (unable to get local issuer certificate)

    1: error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: (unable to get local issuer certificate)

    2: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: (unable to get local issuer certificate)

    3: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889:', src/main.rs:29:6

stack backtrace:

   0: rust_begin_unwind

             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5

   1: core::panicking::panic_fmt

             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14

   2: core::result::unwrap_failed

             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5

   3: tokio::task::local::LocalSet::run_until::{{closure}}

   4: appflowy_cloud::main

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Expected behavior
I thought it wouldn't have an SSL issue, as the domain, s3-appflowy.buildstars.online, has a live and valid SSL certificate generated by letsencrypt. It's not mounted anywhere, but it also shouldn't need to be, as it's a publicly available SSL cert and is not self-signed.

**Desktop (please complete the following information):**

- OS: debian running k3s which is running a deployment which is running the appflowy-cloud container in a pod
- Version: docker image: `appflowyinc/appflowy_cloud:0.0.2`

## Additional Info

s3-apflowy.buildstars.online has a valid and up to date live SSL certificate generated by letsencrypt. I can also verify this is otherwise working by doing:

```console
$ mc ls appflowy
[2023-12-11 10:16:30 CET]     0B appflowy/
[2023-12-11 10:16:30 CET]     0B appflowy-postgres/
```

That `mc` command is using a minio alias called `appflowy` (alias shown below) that uses the same s3 credentials I've given to the appflowy-cloud container and it's able to list both buckets on this minio instance. (postgres also backs up to minio, which is why there's a second bucket in the output)

<details>
<summary>my <code>~/.mc/config.json</code> for reference</summary>

```json
{
  "version": "10",
  "aliases": {
    "appflowy": {
      "url": "https://s3-appflowy.buildstars.online",
      "accessKey": "appflowy",
      "secretKey": "somesecretkeythatsbeenanonymized",
      "api": "s3v4",
      "path": "auto"
    }
  }
}
```

</details>

I tried mounting the certs to a directory rust expects them to be, `/usr/local/ssl/certs` (thanks https://github.com/rust-lang/rustup/issues/2924#issuecomment-990314218), but it still resulted in the same error above.

Thanks as always for any help you can provide. This one is a real noggin scratcher 🤔 I will try to dig into it when I have time, but I'm less good with rust, especially when it comes to SSL issues, which seem to be the real issues I run into with rust 😅
