### ISSUE TITLE
[Bug] Appflowy-cloud does not return a message stating it is ready

### ISSUE THREAD

**Issue by jessebot** [AppFlowy-IO/AppFlowy-Cloud#209]
**Describe the bug**
The appflowy-cloud App State doesn't log that it's ready. I'm not sure how to test if is indeed working.

**To Reproduce**
1. Run appflowy-cloud container built from this repo using the following env vars (via a k8s deployment):

<details>
  <summary>click me for list of all env vars</summary>

```yaml
- name: APP_ENVIRONMENT
  value: production

- name: RUST_LOG
  value: trace

- name: RUST_BACKTRACE
  value: full

- name: APP__GOTRUE__ADMIN_EMAIL
  valueFrom:
    secretKeyRef:
      key: adminEmail
      name: appflowy-gotrue-credentials

- name: APP__GOTRUE__ADMIN_PASSWORD
  valueFrom:
    secretKeyRef:
      key: adminPassword
      name: appflowy-gotrue-credentials

- name: APP__GOTRUE__JWT_SECRET
  valueFrom:
    secretKeyRef:
      key: jwtSecret
      name: appflowy-gotrue-credentials

- name: APP__GOTRUE__EXT_URL
  value: http://gotrue:9999

- name: APP__S3__USE_MINIO
  value: "true"

- name: APP__S3__ACCESS_KEY
  valueFrom:
    secretKeyRef:
      key: accessKeyId
      name: appflowy-s3-credentials

- name: APP__S3__SECRET_KEY
  valueFrom:
    secretKeyRef:
      key: secretAccessKey
      name: appflowy-s3-credentials

- name: APP__S3__REGION
  valueFrom:
    secretKeyRef:
      key: region
      name: appflowy-s3-credentials

- name: APP__S3__BUCKET
  valueFrom:
    secretKeyRef:
      key: bucket
      name: appflowy-s3-credentials

- name: APP__S3__MINIO_URL
  valueFrom:
    secretKeyRef:
      key: endpoint
      name: appflowy-s3-credentials

- name: PGSSLMODE
  value: verify-full

- name: PGSSLCERT
  value: /etc/secrets/postgres/tls.crt

- name: PGSSLKEY
  value: /etc/secrets/postgres/tls.key

- name: PGSSLROOTCERT
  value: /etc/secrets/ca/ca.crt

- name: APP__DATABASE__REQUIRE_SSL
  value: "true"

- name: DATABASE_URL
  valueFrom:
    secretKeyRef:
      key: DATABASE_URL
      name: appflowy-db-secret

- name: APP__DATABASE__HOST
  valueFrom:
    secretKeyRef:
      key: host
      name: appflowy-db-secret

- name: APP__DATABASE__PORT
  valueFrom:
    secretKeyRef:
      key: port
      name: appflowy-db-secret

- name: APP__DATABASE__USERNAME
  valueFrom:
    secretKeyRef:
      key: user
      name: appflowy-db-secret

- name: APP__DATABASE__DATABASE_NAME
  valueFrom:
    secretKeyRef:
      key: database
      name: appflowy-db-secret

- name: REDIS_URI
  value: redis://appflowy-redis-master:6379
```

</details>

4. See logs in container

```json
AppFlowy Cloud with RUST_LOG=trace

{"timestamp":"2023-12-13T09:53:42.929571Z","level":"INFO","fields":{"message":"Preparng to run database migrations..."},"target":"appflowy_cloud::application"}

{"v":0,"name":"appflowy_cloud","msg":"Preparng to run database migrations...","level":30,"hostname":"appflowy-web-app-cloud-5fb8db65d5-76q4k","pid":1,"time":"2023-12-13T09:53:42.92960718Z","target":"appflowy_cloud::application","line":160,"file":"src/application.rs"}

{"timestamp":"2023-12-13T09:53:42.929610Z","level":"INFO","fields":{"message":"Connecting to postgres database with setting: DatabaseSetting { username: \"postgres\", password: \"password\", port: 5432, host: \"appflowy-postgres-rw.appflowy.svc\", database_name: \"appflowy\", require_ssl: true, max_connections: 20 }"},"target":"appflowy_cloud::application"}

{"v":0,"name":"appflowy_cloud","msg":"Connecting to postgres database with setting: DatabaseSetting { username: \"postgres\", password: \"password\", port: 5432, host: \"appflowy-postgres-rw.appflowy.svc\", database_name: \"appflowy\", require_ssl: true, max_connections: 20 }","level":30,"hostname":"appflowy-web-app-cloud-5fb8db65d5-76q4k","pid":1,"time":"2023-12-13T09:53:42.929623802Z","target":"appflowy_cloud::application","line":331,"file":"src/application.rs"}

{"timestamp":"2023-12-13T09:53:43.026021Z","level":"INFO","fields":{"message":"Setting up S3 bucket..."},"target":"appflowy_cloud::application"}

{"v":0,"name":"appflowy_cloud","msg":"Setting up S3 bucket...","level":30,"hostname":"appflowy-web-app-cloud-5fb8db65d5-76q4k","pid":1,"time":"2023-12-13T09:53:43.026032958Z","target":"appflowy_cloud::application","line":165,"file":"src/application.rs"}

{"timestamp":"2023-12-13T09:53:43.030722Z","level":"INFO","fields":{"message":"Connecting to GoTrue..."},"target":"appflowy_cloud::application"}

{"v":0,"name":"appflowy_cloud","msg":"Connecting to GoTrue...","level":30,"hostname":"appflowy-web-app-cloud-5fb8db65d5-76q4k","pid":1,"time":"2023-12-13T09:53:43.030733498Z","target":"appflowy_cloud::application","line":170,"file":"src/application.rs"}

{"timestamp":"2023-12-13T09:53:43.033972Z","level":"INFO","fields":{"message":"Admin user already created and set role to supabase_admin"},"target":"appflowy_cloud::application"}

{"v":0,"name":"appflowy_cloud","msg":"Admin user already created and set role to supabase_admin","level":30,"hostname":"appflowy-web-app-cloud-5fb8db65d5-76q4k","pid":1,"time":"2023-12-13T09:53:43.033984339Z","target":"appflowy_cloud::application","line":254,"file":"src/application.rs"}

{"timestamp":"2023-12-13T09:53:43.033990Z","level":"INFO","fields":{"message":"Connecting to Redis..."},"target":"appflowy_cloud::application"}

{"v":0,"name":"appflowy_cloud","msg":"Connecting to Redis...","level":30,"hostname":"appflowy-web-app-cloud-5fb8db65d5-76q4k","pid":1,"time":"2023-12-13T09:53:43.033995025Z","target":"appflowy_cloud::application","line":175,"file":"src/application.rs"}

{"timestamp":"2023-12-13T09:53:48.827951Z","level":"INFO","fields":{"message":"Setting up Pg listeners..."},"target":"appflowy_cloud::application"}

{"v":0,"name":"appflowy_cloud","msg":"Setting up Pg listeners...","level":30,"hostname":"appflowy-web-app-cloud-5fb8db65d5-76q4k","pid":1,"time":"2023-12-13T09:53:48.827972783Z","target":"appflowy_cloud::application","line":179,"file":"src/application.rs"}

{"timestamp":"2023-12-13T09:53:49.010169Z","level":"INFO","fields":{"message":"Setting up access controls with Casbin..."},"target":"appflowy_cloud::application"}

{"v":0,"name":"appflowy_cloud","msg":"Setting up access controls with Casbin...","level":30,"hostname":"appflowy-web-app-cloud-5fb8db65d5-76q4k","pid":1,"time":"2023-12-13T09:53:49.01018965Z","target":"appflowy_cloud::application","line":184,"file":"src/application.rs"}
```

**Expected behavior**
I would expect this would finish initializing and I would see something in the logs stating this is now initialized and good to go? Is there a status endpoint I can hit at /status or /health or something that I may have missed?

**Desktop (please complete the following information):**
This is via the docker container. I built from the main branch of this repo today after my logging PR was merged using `docker build -t jessebot/appflowy-cloud:0.0.3-linux .` and this time I was on Debian Bookworm.

**Additional context**
I know the code makes it at least here, but I'm not actually sure if it finished:
https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/edbb0dd0df91e3edf6e56c84e7b76c5f80f55f84/src/application.rs#L184

If it has actually finished, I'm happy to add a PR for more logging 💙
