### ISSUE TITLE
[Bug] Failed to run migrations: schema "auth" does not exist

### ISSUE THREAD

**Issue by Rinma** [AppFlowy-IO/AppFlowy-Cloud#228]
When I start my docker with the actual docker-compose file, I get this error:
```
2023-12-20T13:23:15.143476136Z 2023-12-20T13:23:15.143444345Z 30 | v=0 name=appflowy_cloud msg=Connecting to postgres database with setting: DatabaseSetting { pg_conn_opts: PgConnectOptions { host: "appflowy-postgres", port: 5432, socket: None, username: "******", password: Some("******"), database: Some("appflowy"), ssl_mode: Prefer, ssl_root_cert: None, ssl_client_cert: None, ssl_client_key: None, statement_cache_capacity: 100, application_name: None, log_settings: LogSettings { statements_level: Debug, slow_statements_level: Warn, slow_statements_duration: 1s }, extra_float_digits: Some("3"), options: None }, require_ssl: false, max_connections: 20, database_name: "postgres" } hostname=8de62f632969 pid=1 target=appflowy_cloud::application line=332 file=src/application.rs 

2023-12-20T13:23:15.150080834Z Error: Failed to initialize application state: Failed to run migrations: while executing migrations: error returned from database: schema "auth" does not exist
```

I updated my compose file so it uses 
```
- APPFLOWY_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
```

with these values
```env
POSTGRES_USER=******
POSTGRES_PASSWORD=******
POSTGRES_DB=appflowy
POSTGRES_HOST=appflowy-postgres     # name of the docker-compose service
```

But as you can see it the log, it searches for the auth scheme in the database `postgres`.
I'm still learning rust, but for me, it looks like a problem with this code

```rust
db_settings: DatabaseSetting {
      pg_conn_opts: PgConnectOptions::from_str(&get_env_var(
        "APPFLOWY_DATABASE_URL",
        "postgres://postgres:password@localhost:5433/postgres",
      ))?,
      require_ssl: get_env_var("APPFLOWY_DATABASE_REQUIRE_SSL", "false").parse()?,
      max_connections: get_env_var("APPFLOWY_DATABASE_MAX_CONNECTIONS", "20").parse()?,
      database_name: get_env_var("APPFLOWY_DATABASE_NAME", "postgres"),
    },
```

Could it be that it is not using the database name from the `DATABASE_URL` but overrides it with `APPFLOWY_DATABASE_NAME`, which is when not set `postgres`?

So it tried to set the env variable `APPFLOWY_DATABASE_NAME` to `$ {POSTGRES_DB} / appflowy` and the cloud started again.

Here is a screenshot from my database structure:
![grafik](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/1405824/78a9227e-1512-4a30-8194-bc1fa0bf9ad0)

**Comment by speed2exe** [comment]
Hi @Rinma , thanks for the feedback!

`appflowy_cloud` and `gotrue` services shares the same database
`gotrue` is set to take url from `DATABASE_URL`
`appflowy_cloud` is set to take url from `APPFLOWY_DATABASE_URL`
`DATABASE_URL` and `APPFLOWY_DATABASE_URL` should only differs in the login username and password, but the database should kept the same.
From the screenshot, it seems like you have configured `DATABASE_URL` to use `appflowy` database, but appflowy_cloud is using another database.

I think you can solve it by editing `docker-compose.yml` at gotrue section:
```
      - DATABASE_URL=postgres://supabase_auth_admin:root@postgres:5432/${POSTGRES_DB}
```
so that it will use use the same database. Let me know if that solves :)

**Comment by Rinma** [comment]
Hi @speed2exe ,
I think I already have it setup like this, here is my docker-compose file:

<details>
<summary>docker-compose.yml</summary>

```
version: '3'
services:
  appflowy-minio:
    image: minio/minio:latest
    restart: on-failure:2
    labels:
      - "traefik.enable=true"
      - "traefik.network=traefik"

      # Api
      - "traefik.http.routers.appflowy-minio-api.rule=Host(`appflowy.example.org`) && PathPrefix(`/storage`)"
      - "traefik.http.routers.appflowy-minio-api.entrypoints=https"
      - "traefik.http.routers.appflowy-minio-api.middlewares=appflowy-minio-stripprefixes"
      - "traefik.http.routers.appflowy-minio-api.service=appflowy-minio-api"
      
      - "traefik.http.routers.appflowy-minio-api.tls=true"

      - "traefik.http.services.appflowy-minio-api.loadbalancer.server.port=9000"

      # Web
      - "traefik.http.routers.appflowy-minio-https.rule=Host(`appflowy.example.org`) && PathPrefix(`/minio`)"
      - "traefik.http.routers.appflowy-minio-https.entrypoints=https"
      - "traefik.http.routers.appflowy-minio-https.middlewares=appflowy-minio-stripprefixes"
      - "traefik.http.routers.appflowy-minio-https.service=appflowy-minio"
      
      - "traefik.http.routers.appflowy-minio-https.tls=true"

      - "traefik.http.middlewares.appflowy-minio-stripprefixes.stripprefix.prefixes=/minio,/storage"

      - "traefik.http.services.appflowy-minio.loadbalancer.server.port=9001"
    environment:
      - MINIO_BROWSER_REDIRECT_URL=https://appflowy.example.org/minio
    volumes:
      - /opt/appflowy-cloud/data:/data
    networks:
      - appflowy
      - traefik
    command: server /data --console-address ":9001"

  appflowy-postgres:
    restart: on-failure:2
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
    volumes:
      - /opt/appflowy-cloud/migrations/before:/docker-entrypoint-initdb.d
      - /opt/appflowy-cloud/postgres:/var/lib/postgresql/data
    networks:
      - appflowy
  
  appflowy-pgadmin:
    image: dpage/pgadmin4:latest
    restart: on-failure:5
    depends_on:
      - appflowy-postgres
    labels:
      - "traefik.enable=true"
      - "traefik.network=traefik"
    
      - "traefik.http.routers.appflowy-pgadmin-https.rule=Host(`appflowy.example.org`) && PathPrefix(`/pgadmin`)"
      - "traefik.http.routers.appflowy-pgadmin-https.entrypoints=https"
      - "traefik.http.routers.appflowy-pgadmin-https.service=appflowy-pgadmin"
    
      - "traefik.http.routers.appflowy-pgadmin-https.tls=true"
    
      - "traefik.http.services.appflowy-pgadmin.loadbalancer.server.port=80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - SCRIPT_NAME=/pgadmin
    networks:
      - appflowy
      - traefik

  appflowy-redis:
    image: redis:latest
    restart: on-failure:5
    networks:
      - appflowy

  appflowy-gotrue:
    image: registry.example.org/appflowy/gotrue:latest
    restart: on-failure:50
    depends_on:
      - appflowy-postgres
    labels:
      - "traefik.enable=true"
      - "traefik.network=traefik"
      
      - "traefik.http.routers.appflowy-gotrue-https.rule=Host(`appflowy.example.org`) && PathPrefix(`/gotrue`)"
      - "traefik.http.routers.appflowy-gotrue-https.entrypoints=https"
      - "traefik.http.routers.appflowy-gotrue-https.middlewares=appflowy-gotrue-stripprefixes"
      - "traefik.http.routers.appflowy-gotrue-https.service=appflowy-gotrue"
      
      - "traefik.http.routers.appflowy-gotrue-https.tls=true"

      - "traefik.http.middlewares.appflowy-gotrue-stripprefixes.stripprefix.prefixes=/gotrue"
      
      - "traefik.http.services.appflowy-gotrue.loadbalancer.server.port=9999"
    environment:
      # Gotrue config: https://github.com/supabase/gotrue/blob/master/example.env
      - GOTRUE_SITE_URL=appflowy-flutter://                           # redirected to AppFlowy application
      - URI_ALLOW_LIST=*                                                            # adjust restrict if necessary
      - GOTRUE_JWT_SECRET=${GOTRUE_JWT_SECRET}         # authentication secret
      - GOTRUE_DB_DRIVER=postgres
      - API_EXTERNAL_URL=${API_EXTERNAL_URL}
      - DATABASE_URL=postgres://supabase_auth_admin:root@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - PORT=9999

      - GOTRUE_SMTP_HOST=${GOTRUE_SMTP_HOST}                          # e.g. smtp.gmail.com
      - GOTRUE_SMTP_PORT=${GOTRUE_SMTP_PORT}                          # e.g. 465
      - GOTRUE_SMTP_USER=${GOTRUE_SMTP_USER}                          # email sender, e.g. noreply@appflowy.io
      - GOTRUE_SMTP_PASS=${GOTRUE_SMTP_PASS}                           # email password

      - GOTRUE_MAILER_URLPATHS_CONFIRMATION=/gotrue/verify
      - GOTRUE_MAILER_URLPATHS_INVITE=/gotrue/verify
      - GOTRUE_MAILER_URLPATHS_RECOVERY=/gotrue/verify
      - GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE=/gotrue/verify

      - GOTRUE_SMTP_ADMIN_EMAIL=${GOTRUE_SMTP_ADMIN_EMAIL}            # email with admin privileges e.g. internal@appflowy.io
      - GOTRUE_SMTP_MAX_FREQUENCY=${GOTRUE_SMTP_MAX_FREQUENCY:-1ns}   # set to 1ns for running tests
      - GOTRUE_MAILER_AUTOCONFIRM=${GOTRUE_MAILER_AUTOCONFIRM:-false} # change this to true to skip email confirmation

      # Google OAuth config
      - GOTRUE_EXTERNAL_GOOGLE_ENABLED=${GOTRUE_EXTERNAL_GOOGLE_ENABLED}
      - GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID=${GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID}
      - GOTRUE_EXTERNAL_GOOGLE_SECRET=${GOTRUE_EXTERNAL_GOOGLE_SECRET}
      - GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI=${GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI}

      # GITHUB OAuth config
      - GOTRUE_EXTERNAL_GITHUB_ENABLED=${GOTRUE_EXTERNAL_GITHUB_ENABLED}
      - GOTRUE_EXTERNAL_GITHUB_CLIENT_ID=${GOTRUE_EXTERNAL_GITHUB_CLIENT_ID}
      - GOTRUE_EXTERNAL_GITHUB_SECRET=${GOTRUE_EXTERNAL_GITHUB_SECRET}
      - GOTRUE_EXTERNAL_GITHUB_REDIRECT_URI=${GOTRUE_EXTERNAL_GITHUB_REDIRECT_URI}

      # Discord OAuth config
      - GOTRUE_EXTERNAL_DISCORD_ENABLED=${GOTRUE_EXTERNAL_DISCORD_ENABLED}
      - GOTRUE_EXTERNAL_DISCORD_CLIENT_ID=${GOTRUE_EXTERNAL_DISCORD_CLIENT_ID}
      - GOTRUE_EXTERNAL_DISCORD_SECRET=${GOTRUE_EXTERNAL_DISCORD_SECRET}
      - GOTRUE_EXTERNAL_DISCORD_REDIRECT_URI=${GOTRUE_EXTERNAL_DISCORD_REDIRECT_URI}

      # Prometheus Metrics
      - GOTRUE_METRICS_ENABLED=false
      - GOTRUE_METRICS_EXPORTER=prometheus
    networks:
      - appflowy
      - traefik

  appflowy-cloud:
    image: registry.example.org/appflowy/cloud:latest
    restart: on-failure:50
    depends_on:
      - appflowy-redis
      - appflowy-postgres
      - appflowy-gotrue
    labels:
      - "traefik.enable=true"
      - "traefik.network=traefik"
      
      - "traefik.http.routers.appflowy-cloud-https.rule=Host(`appflowy.example.org`) && (PathPrefix(`/api`) || PathPrefix(`/ws`))"
      - "traefik.http.routers.appflowy-cloud-https.entrypoints=https"
      - "traefik.http.routers.appflowy-cloud-https.service=appflowy-cloud"
      
      - "traefik.http.routers.appflowy-cloud-https.tls=true"
      
      - "traefik.http.services.appflowy-cloud.loadbalancer.server.port=8000"
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - APPFLOWY_ENVIRONMENT=production
      - APPFLOWY_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - APPFLOWY_DATABASE_NAME=${POSTGRES_DB}  # <--- **Need to set this to get it working**
      - APPFLOWY_REDIS_URI=redis://appflowy-redis:6379
      - APPFLOWY_GOTRUE_JWT_SECRET=${GOTRUE_JWT_SECRET}
      - APPFLOWY_GOTRUE_BASE_URL=http://appflowy-gotrue:9999
      - APPFLOWY_GOTRUE_EXT_URL=${API_EXTERNAL_URL}
      - APPFLOWY_GOTRUE_ADMIN_EMAIL=${GOTRUE_ADMIN_EMAIL}
      - APPFLOWY_GOTRUE_ADMIN_PASSWORD=${GOTRUE_ADMIN_PASSWORD}
      - APPFLOWY_S3_USE_MINIO=${USE_MINIO}
      - APPFLOWY_S3_MINIO_URL=${MINIO_URL:-http://minio:9000}
      - APPFLOWY_S3_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - APPFLOWY_S3_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
      - APPFLOWY_S3_BUCKET=${AWS_S3_BUCKET}
      - APPFLOWY_S3_REGION=${AWS_REGION}
    networks:
      - appflowy
      - traefik

  appflowy-admin:
    image: registry.example.org/appflowy/admin:latest
    restart: on-failure:50
    depends_on:
      - appflowy-gotrue
    labels:
      - "traefik.enable=true"
      - "traefik.network=traefik"
      
      - "traefik.http.routers.appflowy-admin-https.rule=Host(`appflowy.example.org`)"
      - "traefik.http.routers.appflowy-admin-https.entrypoints=https"
      - "traefik.http.routers.appflowy-admin-https.service=appflowy-admin"
      
      - "traefik.http.routers.appflowy-admin-https.tls=true"
      
      - "traefik.http.services.appflowy-admin.loadbalancer.server.port=3000"
    environment:
      - GOTRUE_URL=http://appflowy-gotrue:9999
      - REDIS_URL=redis://appflowy-redis:6379
    networks:
      - appflowy
      - traefik

networks:
  appflowy:
  traefik:
    external: true
```

Postgres relevant env variables from `.env`
```
POSTGRES_USER=appflowy
POSTGRES_PASSWORD=******
POSTGRES_DB=appflowy
POSTGRES_HOST=appflowy-postgres
```
</details>

But as you can see in the `appflowy-cloud` service, I had to set the `APPFLOWY_DATABASE_NAME` environment variable to make it work. Otherwise, it tries to connect to `postgres` instead of `${POSTGRES_DB}`
