### ISSUE TITLE
Self-hosted with Caddy (TLS termination)

### ISSUE THREAD

**Issue by rubiojr** [AppFlowy-IO/AppFlowy-Cloud#295]
:wave: Howdy friends. Sharing some cloud :cloud: setup and configs required to use Caddy as a NGINX alternative, in case that's of interest.

I've been playing a bit with AppFlowy Cloud self-hosting and a custom [Caddy](https://caddyserver.com/) config, to replace the NGINX TLS termination in [docker-compose.yml](https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/docker-compose.yml), using auto TLS certs from Caddy instead. It was relatively easy to replace, and sync seems to be working as expected after some experimentation.

Steps to replace NGINX with Caddy:

1. Comment out the nginx service in [docker-compose.yml](https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/docker-compose.yml)
2. Add a Caddy service to the compose file:

```yaml
  caddy:
    hostname: caddy
    container_name: caddy
    image: caddy:2
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./caddy/dotcaddy:/root/.caddy # to save certificates on disk
      - ./caddy/dotconfig:/.config # to save certificates on disk
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    environment:
      ACME_AGREE: 'true'
```
3. `mkdir caddy` (inside the AppFlowy-Cloud cloned repo, after following docs [docs](https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/doc/DEPLOYMENT.md#1-getting-source-files)
4. Add a custom `Caddyfile` to `./caddy/Caddyfile`, `replace my.appflowy.domain with your own`:
```
# replace with your own domain
my.appflowy.domain {
  header / Strict-Transport-Security "max-age=15552000; includeSubDomains; preload"

  @options {
    path /api/options
    header Access-Control-Allow-Methods GET,POST,OPTIONS,PUT,DELETE,PATCH
    header Access-Control-Allow-Headers Content-Type,Authorization,Accept,Client-Version
    header Access-Control-Max-Age 3600
    header Content-Type text/plain;charset=utf-8
    header Content-Length 0
  }
  reverse_proxy @options appflowy_cloud:8000

  reverse_proxy /api/* appflowy_cloud:8000
  reverse_proxy /minio/* minio:9001

  handle_path /gotrue/* {
    rewrite * {path}
    reverse_proxy gotrue:9999
  }

  reverse_proxy /ws/* appflowy_cloud:8000

  reverse_proxy /* admin_frontend:3000

  # replace with your email
  tls my-lets-encrypt@email
}

# Not necessary, I think, but exposed it under a custom domain too. Replace with your own domain.
my.gotrue.domain {
  header / Strict-Transport-Security "max-age=15552000; includeSubDomains; preload"

  reverse_proxy gotrue:9999

  # replace with your email
  tls my-lets-encrypt@email
}
```
5. Follow [Deployment docs](https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/doc/DEPLOYMENT.md) to configure the `.env` file
6. Boot containers with `docker compose up`
7. Follow registration docs

Sync seems to be working fine between my laptop and my iOS phone, but it's not a 100% accurate translation of the NGINX config, so it's entirely possible I missed something important.

Thanks a lot for sharing this pretty awesome, cloud-y feature, with us all :heart:
