### ISSUE TITLE
[Bug] Portainer and Traefik Not Found

### ISSUE THREAD

**Issue by projetosfsi** [AppFlowy-IO/AppFlowy-Cloud#744]
**Describe the bug**
Containers leave the docker network and because of this traefik cannot do the reverse proxy

**To Reproduce**
1. Install Portainer and Traefik
2. Create appflowy_network
3. Get on the network appflowy_network in container traefik
4. Create and Deploy Stack APPFLOWY

**Expected behavior**
Containers should all run within the same network and communicate properly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version 128.0.6613.84 (Official Build) (64-bit)

**Additional context**
 - My Stack:

```
services:
  appflowy_cloud:
    image: appflowyinc/appflowy_cloud:0.5.59-amd64
    restart: unless-stopped
    depends_on:
      - appflowy_postgres
      - redis
      - gotrue
    environment:
      - APPFLOWY_DATABASE_URL=postgres://postgres:password@appflowy_postgres:5432/appflowy_db
      - APPFLOWY_REDIS_URI=redis://redis:6379
      - APPFLOWY_GOTRUE_JWT_SECRET=${GOTRUE_JWT_SECRET}
      - APPFLOWY_GOTRUE_BASE_URL=${APPFLOWY_GOTRUE_BASE_URL}
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.appflowy_cloud_api.rule=Host(`appflow.mysite.com`) && PathPrefix(`/api`)"
        - "traefik.http.routers.appflowy_cloud_api.entrypoints=web,websecure"
        - "traefik.http.routers.appflowy_cloud_api.tls.certresolver=leresolver"
        - "traefik.http.routers.appflowy_cloud_ws.rule=Host(`appflow.mysite.com`) && PathPrefix(`/ws`)"
        - "traefik.http.routers.appflowy_cloud_ws.entrypoints=web,websecure"
        - "traefik.http.routers.appflowy_cloud_ws.tls.certresolver=leresolver"
        - "traefik.http.middlewares.appflowy_cloud_cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,PATCH"
        - "traefik.http.middlewares.appflowy_cloud_cors.headers.accesscontrolalloworigin=*"
        - "traefik.http.middlewares.appflowy_cloud_cors.headers.accesscontrolallowheaders=Content-Type,Authorization,Accept,Client-Version"
        - "traefik.http.routers.appflowy_cloud_api.middlewares=appflowy_cloud_cors"
        - "traefik.http.services.appflowy_cloud_api.loadbalancer.server.port=8000"
        - "traefik.http.services.appflowy_cloud_ws.loadbalancer.server.port=8000"
    networks:
      - appflowy_network

  gotrue:
    image: appflowyinc/gotrue:0.5.59
    restart: unless-stopped
    depends_on:
      - gotrue_postgres
    environment:
      - GOTRUE_JWT_SECRET=${GOTRUE_JWT_SECRET}
      - GOTRUE_DATABASE_URL=postgres://postgres:password@gotrue_postgres:5432/gotrue_db
      - GOTRUE_SITE_URL=${APPFLOWY_GOTRUE_BASE_URL}
      - API_EXTERNAL_URL=${API_EXTERNAL_URL}
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gotrue.rule=Host(`appflow.mysite.com`) && PathPrefix(`/gotrue`)"
        - "traefik.http.routers.gotrue.entrypoints=web"
        - "traefik.http.services.gotrue.loadbalancer.server.port=9999"
    networks:
      - appflowy_network

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - appflowy_network

  appflowy_postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appflowy_db
    volumes:
      - appflowy_postgres_data:/var/lib/postgresql/data
    networks:
      - appflowy_network

  gotrue_postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gotrue_db
    volumes:
      - gotrue_postgres_data:/var/lib/postgresql/data
    networks:
      - appflowy_network

  admin_frontend:
    image: appflowyinc/admin_frontend:0.5.59-amd64
    restart: unless-stopped
    depends_on:
      - gotrue
      - redis
    environment:
      - ADMIN_FRONTEND_REDIS_URL=${ADMIN_FRONTEND_REDIS_URL}
      - ADMIN_FRONTEND_GOTRUE_URL=${ADMIN_FRONTEND_GOTRUE_URL}
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.admin_frontend.rule=Host(`appflow.mysite.com`) && PathPrefix(`/`)"
        - "traefik.http.routers.admin_frontend.entrypoints=web"
        - "traefik.http.services.admin_frontend.loadbalancer.server.port=3000"
    networks:
      - appflowy_network

  ai:
    image: appflowyinc/appflowy_ai:0.6.6
    restart: unless-stopped
    depends_on:
      - appflowy_cloud
    environment:
      - OPENAI_API_KEY=${APPFLOWY_AI_OPENAI_API_KEY}
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ai.rule=Host(`appflow.mysite.com`) && PathPrefix(`/ai`)"
        - "traefik.http.routers.ai.entrypoints=web"
        - "traefik.http.services.ai.loadbalancer.server.port=5001"
    networks:
      - appflowy_network

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pgadmin.rule=Host(`appflow.mysite.com`) && PathPrefix(`/pgadmin`)"
        - "traefik.http.routers.pgadmin.entrypoints=web"
        - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
    networks:
      - appflowy_network

  minio:
    image: minio/minio
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=${APPFLOWY_S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${APPFLOWY_S3_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.minio.rule=Host(`appflow.mysite.com`) && PathPrefix(`/minio`)"
        - "traefik.http.routers.minio.entrypoints=web"
        - "traefik.http.services.minio.loadbalancer.server.port=9001"
    networks:
      - appflowy_network

volumes:
  appflowy_postgres_data:
  gotrue_postgres_data:
  minio_data:

networks:
  appflowy_network:
    external: true

```
